// Single source of truth for company_event workflow status (spec §10 "Compliance
// Workflow and Statuses"). Lives here (not in CompanyEventService.js) so it can be
// required by CompanyEventService.js, EntityCompanyService.js, and
// CommonCronService.js without any risk of a circular require.

const EVENT_STATUS = {
    PENDING: 'PENDING',
    IN_PREPARATION: 'IN_PREPARATION',
    AWAITING_DOCUMENTS: 'AWAITING_DOCUMENTS',
    AWAITING_CLIENT: 'AWAITING_CLIENT',
    AWAITING_APPROVAL: 'AWAITING_APPROVAL',
    READY_TO_FILE: 'READY_TO_FILE',
    FILED: 'FILED',
    COMPLETED: 'COMPLETED',
    WAIVED: 'WAIVED',
    DISPENSE: 'DISPENSE',
    EXEMPT: 'EXEMPT',
    CANCELLED: 'CANCELLED',
    NOT_APPLICABLE: 'NOT_APPLICABLE',
};

const EVENT_STATUS_VALUES = Object.values(EVENT_STATUS);

// "Open" = still eligible for reminders and still eligible to be marked OVERDUE.
// Drives CommonCronService's reminder-eligibility filter and
// CompanyEventService._eventDisplayStatus's OVERDUE/UPCOMING/NOT_STARTED computation.
const OPEN_EVENT_STATUSES = [
    EVENT_STATUS.PENDING,
    EVENT_STATUS.IN_PREPARATION,
    EVENT_STATUS.AWAITING_DOCUMENTS,
    EVENT_STATUS.AWAITING_CLIENT,
    EVENT_STATUS.AWAITING_APPROVAL,
    EVENT_STATUS.READY_TO_FILE,
];

// Manual workflow transitions only (via updateEventWorkflowStatus). COMPLETED is
// never a manual target here — it stays auto-derived from filing_date through the
// existing _resolveEventStatus rule.
const ALLOWED_STATUS_TRANSITIONS = {
    [EVENT_STATUS.PENDING]: [
        EVENT_STATUS.IN_PREPARATION, EVENT_STATUS.AWAITING_DOCUMENTS, EVENT_STATUS.AWAITING_CLIENT,
        EVENT_STATUS.READY_TO_FILE, EVENT_STATUS.NOT_APPLICABLE, EVENT_STATUS.CANCELLED,
    ],
    [EVENT_STATUS.IN_PREPARATION]: [
        EVENT_STATUS.AWAITING_DOCUMENTS, EVENT_STATUS.AWAITING_CLIENT, EVENT_STATUS.AWAITING_APPROVAL,
        EVENT_STATUS.READY_TO_FILE, EVENT_STATUS.CANCELLED,
    ],
    [EVENT_STATUS.AWAITING_DOCUMENTS]: [
        EVENT_STATUS.IN_PREPARATION, EVENT_STATUS.AWAITING_APPROVAL, EVENT_STATUS.READY_TO_FILE, EVENT_STATUS.CANCELLED,
    ],
    [EVENT_STATUS.AWAITING_CLIENT]: [
        EVENT_STATUS.IN_PREPARATION, EVENT_STATUS.AWAITING_APPROVAL, EVENT_STATUS.READY_TO_FILE, EVENT_STATUS.CANCELLED,
    ],
    [EVENT_STATUS.AWAITING_APPROVAL]: [
        EVENT_STATUS.READY_TO_FILE, EVENT_STATUS.IN_PREPARATION, EVENT_STATUS.CANCELLED,
    ],
    [EVENT_STATUS.READY_TO_FILE]: [
        EVENT_STATUS.FILED, EVENT_STATUS.IN_PREPARATION, EVENT_STATUS.CANCELLED,
    ],
    [EVENT_STATUS.FILED]: [EVENT_STATUS.COMPLETED],
};

module.exports = {
    EVENT_STATUS,
    EVENT_STATUS_VALUES,
    OPEN_EVENT_STATUSES,
    ALLOWED_STATUS_TRANSITIONS,
};
