import { MasterResourceConfig } from '../types/settings.types';

export const MASTER_RESOURCES: MasterResourceConfig[] = [
  {
    id: 'salutation',
    title: 'Salutations',
    group: 'common',
    listPath: '/salutation/list',
    createPath: '/salutation/create',
    updatePath: (id) => `/salutation/update/${id}`,
    deletePath: '/salutation/delete',
    idField: 'salutation_id',
    labelField: 'salutation_name',
    order: 'salutation_id:ASC',
    fields: [{ key: 'salutation_name', label: 'Salutation Name', required: true }],
  },
  {
    id: 'region',
    title: 'Regions',
    group: 'common',
    listPath: '/region-master/list',
    createPath: '/region-master/create',
    updatePath: (id) => `/region-master/update/${id}`,
    deletePath: '/region-master/delete',
    idField: 'region_id',
    labelField: 'region_name',
    order: 'region_id:ASC',
    fields: [{ key: 'region_name', label: 'Region Name', required: true }],
  },
  {
    id: 'race',
    title: 'Races',
    group: 'common',
    listPath: '/race-master/list',
    createPath: '/race-master/create',
    updatePath: (id) => `/race-master/update/${id}`,
    deletePath: '/race-master/delete',
    idField: 'race_id',
    labelField: 'race_name',
    order: 'race_id:ASC',
    fields: [{ key: 'race_name', label: 'Race Name', required: true }],
  },
  {
    id: 'tag',
    title: 'Tags',
    group: 'common',
    listPath: '/tag/list',
    createPath: '/tag/create',
    updatePath: (id) => `/tag/update/${id}`,
    deletePath: '/tag/delete',
    idField: 'tag_id',
    labelField: 'tag_name',
    order: 'tag_id:ASC',
    fields: [
      { key: 'tag_name', label: 'Tag Name', required: true },
      { key: 'tag_color', label: 'Color', placeholder: '#405189' },
    ],
  },
  {
    id: 'company-type',
    title: 'Company Types',
    group: 'company',
    listPath: '/company-type/list',
    createPath: '/company-type/create',
    updatePath: (id) => `/company-type/update/${id}`,
    deletePath: '/company-type/delete',
    idField: 'company_type_id',
    labelField: 'company_type_name',
    order: 'company_type_order:ASC',
    fields: [
      { key: 'company_type_name', label: 'Company Type Name', required: true },
      { key: 'company_type_order', label: 'Order', type: 'number' },
    ],
  },
  {
    id: 'company-segregation',
    title: 'Company Segregations',
    group: 'company',
    listPath: '/company-segregation/list',
    createPath: '/company-segregation/create',
    updatePath: (id) => `/company-segregation/update/${id}`,
    deletePath: '/company-segregation/delete',
    idField: 'segregation_id',
    labelField: 'segregation_name',
    order: 'segregation_id:ASC',
    fields: [{ key: 'segregation_name', label: 'Segregation Name', required: true }],
  },
  {
    id: 'company-ssic-code',
    title: 'Company SSIC Codes',
    group: 'company',
    listPath: '/company-ssic-code/list',
    createPath: '/company-ssic-code/create',
    updatePath: (id) => `/company-ssic-code/update/${id}`,
    deletePath: '/company-ssic-code/delete',
    idField: 'ssic_id',
    labelField: 'ssic_code',
    order: 'ssic_id:ASC',
    fields: [
      { key: 'ssic_code', label: 'SSIC Code', required: true },
      { key: 'ssic_description', label: 'Description', required: true },
      { key: 'country', label: 'Country', placeholder: 'Singapore' },
      { key: 'country_code', label: 'Country Code', placeholder: 'SG' },
    ],
  },
  {
    id: 'company-event-name',
    title: 'Company Events',
    group: 'company',
    listPath: '/company-event-name/list',
    createPath: '/company-event-name/create',
    updatePath: (id) => `/company-event-name/update/${id}`,
    deletePath: '/company-event-name/delete',
    idField: 'e_id',
    labelField: 'event_name',
    order: 'e_id:ASC',
    fields: [
      { key: 'event_type', label: 'Event Type', required: true },
      { key: 'event_name', label: 'Event Name', required: true },
      { key: 'event_subject', label: 'Event Subject' },
      { key: 'color_code', label: 'Color', placeholder: '#3788D8' },
    ],
  },
  {
    id: 'business-entity',
    title: 'Business Entities',
    group: 'company',
    listPath: '/business-entity/list',
    createPath: '/business-entity/create',
    updatePath: (id) => `/business-entity/update/${id}`,
    deletePath: '/business-entity/delete',
    idField: 'bn_id',
    labelField: 'bs_name',
    order: 'bn_id:ASC',
    fields: [{ key: 'bs_name', label: 'Business Entity Name', required: true }],
  },
  {
    id: 'entity-status',
    title: 'Entity Status',
    group: 'company',
    listPath: '/entity-status/list',
    createPath: '/entity-status/create',
    updatePath: (id) => `/entity-status/update/${id}`,
    deletePath: '/entity-status/delete',
    idField: 'e_status_id',
    labelField: 'e_status_name',
    order: 'e_status_id:ASC',
    fields: [{ key: 'e_status_name', label: 'Status Name', required: true }],
  },
  {
    id: 'share-class',
    title: 'Share Classes',
    group: 'share',
    listPath: '/share-class-master/list',
    createPath: '/share-class-master/create',
    updatePath: (id) => `/share-class-master/update/${id}`,
    deletePath: '/share-class-master/delete',
    idField: 'sc_id',
    labelField: 'sc_name',
    order: 'sc_id:ASC',
    fields: [
      { key: 'sc_name', label: 'Share Class Name', required: true },
      {
        key: 'sc_type',
        label: 'Type',
        type: 'select',
        required: true,
        options: [
          { label: 'Ordinary', value: 'Ordinary' },
          { label: 'Preference', value: 'Preference' },
        ],
      },
    ],
  },
  {
    id: 'transaction-type',
    title: 'Transaction Types',
    group: 'share',
    listPath: '/transaction-type/list',
    createPath: '/transaction-type/create',
    updatePath: (id) => `/transaction-type/update/${id}`,
    deletePath: '/transaction-type/delete',
    idField: 't_id',
    labelField: 't_name',
    order: 't_order:ASC',
    fields: [
      {
        key: 't_type',
        label: 'Level',
        type: 'select',
        required: true,
        options: [
          { label: 'Company', value: '1' },
          { label: 'Shareholder', value: '2' },
        ],
      },
      { key: 't_name', label: 'Transaction Name', required: true },
      { key: 't_order', label: 'Order', type: 'number' },
    ],
  },
  {
    id: 'member-id-type',
    title: 'Member ID Types',
    group: 'official',
    listPath: '/member-id-type/list',
    createPath: '/member-id-type/create',
    updatePath: (id) => `/member-id-type/update/${id}`,
    deletePath: '/member-id-type/delete',
    idField: 'm_identification_id',
    labelField: 'id_name',
    order: 'm_identification_id:ASC',
    fields: [
      { key: 'id_name', label: 'ID Type Name', required: true },
      { key: 'country_code', label: 'Country Code', placeholder: 'SG' },
    ],
  },
];

export function getMasterResourcesByGroup(groupId: string) {
  return MASTER_RESOURCES.filter((resource) => resource.group === groupId);
}

export function getMasterResource(resourceId: string) {
  return MASTER_RESOURCES.find((resource) => resource.id === resourceId);
}
