'use strict';

// Common application-owned catalogue deployed into every tenant database.
// This contains no tenant form or company data.
module.exports = Object.freeze([
    { key: 'company.name', label: 'Company Name', domain: 'COMPANY', resolver: 'ENTITY_FIELD', path: 'entity.name', type: 'STRING', order: 1, aliases: ['Company_name'] },
    { key: 'company.registration_number', label: 'Register Number', domain: 'COMPANY', resolver: 'PRIMARY_IDENTIFICATION', path: 'identification.registration_number', type: 'STRING', order: 2, aliases: ['Company_registration_number'] },
    { key: 'company.registered_address', label: 'Registered Office Address', domain: 'COMPANY', resolver: 'ENTITY_ADDRESS', path: 'addresses.registered', type: 'ADDRESS', order: 3 },
    { key: 'company.local_address', label: 'Local Address', domain: 'COMPANY', resolver: 'ENTITY_ADDRESS', path: 'addresses.local', type: 'ADDRESS', order: 4 },
    { key: 'company.foreign_address', label: 'Foreign Address', domain: 'COMPANY', resolver: 'ENTITY_ADDRESS', path: 'addresses.foreign', type: 'ADDRESS', order: 5 },
    { key: 'company.incorporation_date', label: 'Incorporation Date', domain: 'COMPANY', resolver: 'COMPANY_DETAIL_FIELD', path: 'company_detail.company_incorporation_date', type: 'DATE', order: 6, formats: ['DD-MMM-YYYY', 'DD/MM/YYYY', 'YYYY-MM-DD'] },
    { key: 'company.strike_off_or_dissolved_date', label: 'Strike-off / Dissolved Date', domain: 'COMPANY', resolver: 'COMPANY_PROFILE', path: 'company_profile.strike_off_or_dissolved_date', type: 'DATE', order: 7, formats: ['DD-MMM-YYYY', 'DD/MM/YYYY', 'YYYY-MM-DD'] },
    { key: 'company.country', label: 'Country', domain: 'COMPANY', resolver: 'COMPANY_DETAIL_FIELD', path: 'company_detail.country', type: 'STRING', order: 8 },
    { key: 'company.bank_name', label: 'Company Bank Name', domain: 'COMPANY', resolver: 'COMPANY_PROFILE', path: 'company_profile.bank_name', type: 'STRING', order: 9, description: 'Company bank name. Requires a configured bank master model for the stored bank reference.' },
    { key: 'company.ssic_code_1', label: 'SSIC Code 1', domain: 'COMPANY', resolver: 'COMPANY_PROFILE', path: 'company_profile.ssic_code_1', type: 'STRING', order: 10 },
    { key: 'company.ssic_description_1', label: 'SSIC Description 1', domain: 'COMPANY', resolver: 'COMPANY_PROFILE', path: 'company_profile.ssic_description_1', type: 'TEXT', order: 11 },
    { key: 'company.ssic_code_2', label: 'SSIC Code 2', domain: 'COMPANY', resolver: 'COMPANY_PROFILE', path: 'company_profile.ssic_code_2', type: 'STRING', order: 12 },
    { key: 'company.ssic_description_2', label: 'SSIC Description 2', domain: 'COMPANY', resolver: 'COMPANY_PROFILE', path: 'company_profile.ssic_description_2', type: 'TEXT', order: 13 },
    { key: 'company.new_name', label: 'New Company Name', domain: 'COMPANY', resolver: 'COMPANY_PROFILE', path: 'company_profile.new_name', type: 'STRING', order: 14 },
    { key: 'company.old_name', label: 'Old Company Name', domain: 'COMPANY', resolver: 'COMPANY_PROFILE', path: 'company_profile.old_name', type: 'STRING', order: 15 },
    { key: 'company.old_name_effective_date', label: 'Old Company Name Effective Date', domain: 'COMPANY', resolver: 'COMPANY_PROFILE', path: 'company_profile.old_name_effective_date', type: 'DATE', order: 16, formats: ['DD-MMM-YYYY', 'DD/MM/YYYY', 'YYYY-MM-DD'] },
    { key: 'company.new_registered_address', label: 'New Registered Office Address', domain: 'COMPANY', resolver: 'COMPANY_PROFILE', path: 'company_profile.new_registered_address', type: 'ADDRESS', order: 17 },
    { key: 'company.old_registered_address', label: 'Old Registered Office Address', domain: 'COMPANY', resolver: 'COMPANY_PROFILE', path: 'company_profile.old_registered_address', type: 'ADDRESS', order: 18 },
    { key: 'company.old_registered_address_effective_date', label: 'Old Registered Office Address Effective Date', domain: 'COMPANY', resolver: 'COMPANY_PROFILE', path: 'company_profile.old_registered_address_effective_date', type: 'DATE', order: 19, formats: ['DD-MMM-YYYY', 'DD/MM/YYYY', 'YYYY-MM-DD'] },
    { key: 'company.former_name', label: 'Former Company Name', domain: 'COMPANY', resolver: 'ENTITY_FIELD', path: 'entity.former_name', type: 'STRING', order: 20 },
    { key: 'company.client_number', label: 'Client Number', domain: 'COMPANY', resolver: 'ENTITY_FIELD', path: 'entity.client_no', type: 'STRING', order: 21 },
    { key: 'company.financial_year_end', label: 'Financial Year End', domain: 'COMPANY', resolver: 'COMPANY_DETAIL_FIELD', path: 'company_detail.company_fin_date', type: 'DATE', order: 22, formats: ['DD-MMM-YYYY', 'DD/MM/YYYY', 'YYYY-MM-DD'] },
    { key: 'company.primary_email', label: 'Primary Email', domain: 'COMPANY', resolver: 'ENTITY_CONTACT', path: 'contacts.primary_email', type: 'EMAIL', order: 23 },
    { key: 'officials.all', label: 'All Current Officials', domain: 'OFFICIAL', resolver: 'CURRENT_OFFICIALS', path: 'officials.all', type: 'JSON', order: 22, collection: true, selection: 'ALL' },
    // Loop block over every current official. Body tokens read the mapped
    // official directly ({{name}}, {{role_name}}, {{appointment_date}}) or via
    // the picker's scoped form ({{all_officials##official_record.name}}).
    { key: 'officials.all_list', label: 'Official List', domain: 'OFFICIAL', resolver: 'CURRENT_OFFICIALS', path: 'officials.all', type: 'JSON', order: 23, collection: true, selection: 'SELECT_MANY' },
    { key: 'officials.directors', label: 'Current Directors', domain: 'OFFICIAL', resolver: 'CURRENT_OFFICIALS', path: 'officials.directors', type: 'JSON', order: 24, collection: true, selection: 'ALL', roleTags: ['director'] },
    { key: 'officials.secretaries', label: 'Current Secretaries', domain: 'OFFICIAL', resolver: 'CURRENT_OFFICIALS', path: 'officials.secretaries', type: 'JSON', order: 25, collection: true, selection: 'SELECT_MANY', roleTags: ['secretary'] },
    { key: 'officials.shareholders', label: 'Current Shareholders', domain: 'OFFICIAL', resolver: 'CURRENT_OFFICIALS', path: 'officials.shareholders', type: 'JSON', order: 26, collection: true, selection: 'SELECT_MANY', roleTags: ['shareholder'] },
    { key: 'share.shareholder_name', label: 'Shareholder name', domain: 'SHARE', resolver: 'SHARE_DETAIL', path: 'share_detail.shareholder_name', type: 'STRING', order: 1 },
    { key: 'share.shareholder_address', label: 'Shareholder Address', domain: 'SHARE', resolver: 'SHARE_DETAIL', path: 'share_detail.shareholder_address', type: 'ADDRESS', order: 2 },
    { key: 'share.shareholder_identification_type', label: 'Shareholder ID type', domain: 'SHARE', resolver: 'SHARE_DETAIL', path: 'share_detail.shareholder_identification_type', type: 'STRING', order: 3 },
    { key: 'share.shareholder_identification_number', label: 'Shareholder NRIC No.', domain: 'SHARE', resolver: 'SHARE_DETAIL', path: 'share_detail.shareholder_identification_number', type: 'STRING', order: 4 },
    { key: 'share.currency', label: 'Currency', domain: 'SHARE', resolver: 'SHARE_DETAIL', path: 'share_detail.currency', type: 'STRING', order: 5 },
    { key: 'share.shareholder_nationality', label: 'Shareholder Nationality', domain: 'SHARE', resolver: 'SHARE_DETAIL', path: 'share_detail.shareholder_nationality', type: 'STRING', order: 6 },
    { key: 'share.shareholder_phone', label: 'Shareholder Phone', domain: 'SHARE', resolver: 'SHARE_DETAIL', path: 'share_detail.shareholder_phone', type: 'STRING', order: 7 },
    { key: 'share.shareholder_mobile', label: 'Shareholder Mobile', domain: 'SHARE', resolver: 'SHARE_DETAIL', path: 'share_detail.shareholder_mobile', type: 'STRING', order: 8 },
    { key: 'share.share_certificate_number', label: 'Share Cert No', domain: 'SHARE', resolver: 'SHARE_DETAIL', path: 'share_detail.share_certificate_number', type: 'STRING', order: 9 },
    { key: 'share.number_of_shares', label: 'No of Share', domain: 'SHARE', resolver: 'SHARE_DETAIL', path: 'share_detail.number_of_shares', type: 'DECIMAL', order: 10 },
    { key: 'share.price_per_share', label: 'Price per share', domain: 'SHARE', resolver: 'SHARE_DETAIL', path: 'share_detail.price_per_share', type: 'DECIMAL', order: 11 },
    { key: 'share.number_of_shares_in_words', label: 'No of Share in word(Spelt out)', domain: 'SHARE', resolver: 'SHARE_DETAIL', path: 'share_detail.number_of_shares_in_words', type: 'STRING', order: 12 },
    { key: 'share.cash_paid_up_capital', label: 'Cash Paid Up Capital', domain: 'SHARE', resolver: 'SHARE_DETAIL', path: 'share_detail.cash_paid_up_capital', type: 'MONEY', order: 13 },
    { key: 'share.cash_paid_up_capital_in_words', label: 'Cash Paid Up Capital - Word', domain: 'SHARE', resolver: 'SHARE_DETAIL', path: 'share_detail.cash_paid_up_capital_in_words', type: 'STRING', order: 14 },
    { key: 'share.consideration_paid_up_capital', label: 'Consideration Paid Up Capital', domain: 'SHARE', resolver: 'SHARE_DETAIL', path: 'share_detail.consideration_paid_up_capital', type: 'MONEY', order: 15 },
    { key: 'share.consideration_paid_up_capital_in_words', label: 'Consideration Paid Up Capital - Word', domain: 'SHARE', resolver: 'SHARE_DETAIL', path: 'share_detail.consideration_paid_up_capital_in_words', type: 'STRING', order: 16 },
    { key: 'share.total_paid_up_capital', label: 'Cash + Consideration Paid Up Capital', domain: 'SHARE', resolver: 'SHARE_DETAIL', path: 'share_detail.total_paid_up_capital', type: 'MONEY', order: 17 },
    { key: 'share.transferor_name', label: 'Transferor Name', domain: 'SHARE', resolver: 'SHARE_DETAIL', path: 'share_detail.transferor_name', type: 'STRING', order: 18 },
    { key: 'share.transferor_identification_type', label: 'Transferor ID type', domain: 'SHARE', resolver: 'SHARE_DETAIL', path: 'share_detail.transferor_identification_type', type: 'STRING', order: 19 },
    { key: 'share.transferor_identification_number', label: 'Transferor ID No.', domain: 'SHARE', resolver: 'SHARE_DETAIL', path: 'share_detail.transferor_identification_number', type: 'STRING', order: 20 },
    { key: 'share.transferor_address', label: 'Transferor Address', domain: 'SHARE', resolver: 'SHARE_DETAIL', path: 'share_detail.transferor_address', type: 'ADDRESS', order: 21 },
    { key: 'share.transferee_name', label: 'Transferee Name', domain: 'SHARE', resolver: 'SHARE_DETAIL', path: 'share_detail.transferee_name', type: 'STRING', order: 22 },
    { key: 'share.transferee_identification_type', label: 'Transferee ID Type', domain: 'SHARE', resolver: 'SHARE_DETAIL', path: 'share_detail.transferee_identification_type', type: 'STRING', order: 23 },
    { key: 'share.transferee_identification_number', label: 'Transferee ID No.', domain: 'SHARE', resolver: 'SHARE_DETAIL', path: 'share_detail.transferee_identification_number', type: 'STRING', order: 24 },
    { key: 'share.transferee_address', label: 'Transferee Address', domain: 'SHARE', resolver: 'SHARE_DETAIL', path: 'share_detail.transferee_address', type: 'ADDRESS', order: 25 },
    { key: 'share.transfer_amount_of_shares', label: 'Transfer amount of share', domain: 'SHARE', resolver: 'SHARE_DETAIL', path: 'share_detail.transfer_amount_of_shares', type: 'DECIMAL', order: 26 },
    { key: 'official_record.name', label: 'Name', domain: 'OFFICIAL', resolver: 'SELECTED_OFFICIAL', path: 'official_record.name', type: 'STRING', order: 1 },
    { key: 'official_record.occupation', label: 'Occupation', domain: 'OFFICIAL', resolver: 'SELECTED_OFFICIAL', path: 'official_record.occupation', type: 'STRING', order: 2 },
    { key: 'official_record.date_of_birth', label: 'DOB', domain: 'OFFICIAL', resolver: 'SELECTED_OFFICIAL', path: 'official_record.date_of_birth', type: 'DATE', order: 3, formats: ['DD-MMM-YYYY', 'DD/MM/YYYY', 'YYYY-MM-DD'] },
    { key: 'official_record.nationality', label: 'Nationality', domain: 'OFFICIAL', resolver: 'SELECTED_OFFICIAL', path: 'official_record.nationality', type: 'STRING', order: 4 },
    { key: 'official_record.identification_number', label: 'ID.No', domain: 'OFFICIAL', resolver: 'SELECTED_OFFICIAL', path: 'official_record.identification_number', type: 'STRING', order: 5 },
    { key: 'official_record.identification_type', label: 'ID Type', domain: 'OFFICIAL', resolver: 'SELECTED_OFFICIAL', path: 'official_record.identification_type', type: 'STRING', order: 6 },
    { key: 'official_record.default_address', label: 'Default Address', domain: 'OFFICIAL', resolver: 'SELECTED_OFFICIAL', path: 'official_record.default_address', type: 'ADDRESS', order: 7 },
    { key: 'official_record.alternate_address', label: 'Alternate Address', domain: 'OFFICIAL', resolver: 'SELECTED_OFFICIAL', path: 'official_record.alternate_address', type: 'ADDRESS', order: 8 },
    { key: 'official_record.contact_number', label: 'Contact Number', domain: 'OFFICIAL', resolver: 'SELECTED_OFFICIAL', path: 'official_record.contact_number', type: 'STRING', order: 9 },
    { key: 'official_record.telephone', label: 'Telephone', domain: 'OFFICIAL', resolver: 'SELECTED_OFFICIAL', path: 'official_record.telephone', type: 'STRING', order: 10 },
    { key: 'official_record.appointment_date', label: 'Appointment Date', domain: 'OFFICIAL', resolver: 'SELECTED_OFFICIAL', path: 'official_record.appointment_date', type: 'DATE', order: 11, formats: ['DD-MMM-YYYY', 'DD/MM/YYYY', 'YYYY-MM-DD'] },
    { key: 'official_record.designation_or_occupation', label: 'Designation / Occupation', domain: 'OFFICIAL', resolver: 'SELECTED_OFFICIAL', path: 'official_record.designation_or_occupation', type: 'STRING', order: 12 },
    { key: 'official_record.role', label: 'Selected Official Role Code', domain: 'OFFICIAL', resolver: 'SELECTED_OFFICIAL', path: 'official_record.role', type: 'STRING', order: 13 },
    { key: 'official_record.role_name', label: 'Selected Official Role', domain: 'OFFICIAL', resolver: 'SELECTED_OFFICIAL', path: 'official_record.role_name', type: 'STRING', order: 14 },
    { key: 'official_record.cessation_date', label: 'Official Cessation Date', domain: 'OFFICIAL', resolver: 'SELECTED_OFFICIAL', path: 'official_record.cessation_date', type: 'DATE', order: 15, formats: ['DD-MMM-YYYY', 'DD/MM/YYYY', 'YYYY-MM-DD'] },
    { key: 'official_record.status', label: 'Official Status', domain: 'OFFICIAL', resolver: 'SELECTED_OFFICIAL', path: 'official_record.status', type: 'STRING', order: 16 },
    { key: 'official_record.company_type', label: 'Company Type', domain: 'OFFICIAL', resolver: 'SELECTED_OFFICIAL', path: 'official_record.company_type', type: 'STRING', order: 17, description: 'Company type of the selected corporate official.' },
    { key: 'official_record.country', label: 'Country', domain: 'OFFICIAL', resolver: 'SELECTED_OFFICIAL', path: 'official_record.country', type: 'STRING', order: 18, description: 'Country of the selected corporate official.' },
    { key: 'official_record.incorporation_date', label: 'Incorporation date', domain: 'OFFICIAL', resolver: 'SELECTED_OFFICIAL', path: 'official_record.incorporation_date', type: 'DATE', order: 19, formats: ['DD-MMM-YYYY', 'DD/MM/YYYY', 'YYYY-MM-DD'], description: 'Incorporation date of the selected corporate official.' },
    { key: 'official_record.registered_company_address', label: 'Registered company address', domain: 'OFFICIAL', resolver: 'SELECTED_OFFICIAL', path: 'official_record.registered_company_address', type: 'ADDRESS', order: 20, description: 'Registered company address of the selected corporate official.' },
    { key: 'official_record.registration_number', label: 'Registration Number(UEN/FBRM/DB/ACRA)', domain: 'OFFICIAL', resolver: 'SELECTED_OFFICIAL', path: 'official_record.registration_number', type: 'STRING', order: 21, description: 'UEN, FBRN, UF/DB, ACRA, or fallback registration number of the selected corporate official.' },
    { key: 'event.slug', label: 'Event Code', domain: 'EVENT', resolver: 'EVENT_FIELD', path: 'event.event_slug', type: 'STRING' },
    { key: 'event.period_start', label: 'Event Period Start', domain: 'EVENT', resolver: 'EVENT_FIELD', path: 'event.period_start', type: 'DATE', formats: ['DD-MMM-YYYY', 'DD/MM/YYYY', 'YYYY-MM-DD'] },
    { key: 'event.period_end', label: 'Event Period End', domain: 'EVENT', resolver: 'EVENT_FIELD', path: 'event.period_end', type: 'DATE', formats: ['DD-MMM-YYYY', 'DD/MM/YYYY', 'YYYY-MM-DD'] },
    { key: 'event.financial_year_end', label: 'Event Financial Year End', domain: 'EVENT', resolver: 'EVENT_FIELD', path: 'event.fye_date', type: 'DATE', formats: ['DD-MMM-YYYY', 'DD/MM/YYYY', 'YYYY-MM-DD'] },
    { key: 'event.due_date', label: 'Event Due Date', domain: 'EVENT', resolver: 'EVENT_FIELD', path: 'event.due_date', type: 'DATE', formats: ['DD-MMM-YYYY', 'DD/MM/YYYY', 'YYYY-MM-DD'] },
    { key: 'event.extended_due_date', label: 'Extended Due Date', domain: 'EVENT', resolver: 'EVENT_FIELD', path: 'event.extended_due_date', type: 'DATE', formats: ['DD-MMM-YYYY', 'DD/MM/YYYY', 'YYYY-MM-DD'] },
    { key: 'event.held_date', label: 'Event Held Date', domain: 'EVENT', resolver: 'EVENT_FIELD', path: 'event.held_date', type: 'DATE', formats: ['DD-MMM-YYYY', 'DD/MM/YYYY', 'YYYY-MM-DD'] },
    { key: 'event.filing_date', label: 'Event Filing Date', domain: 'EVENT', resolver: 'EVENT_FIELD', path: 'event.filing_date', type: 'DATE', formats: ['DD-MMM-YYYY', 'DD/MM/YYYY', 'YYYY-MM-DD'] },
    { key: 'event.status', label: 'Event Status', domain: 'EVENT', resolver: 'EVENT_FIELD', path: 'event.status', type: 'STRING' },
    { key: 'event.venue', label: 'Event Venue', domain: 'EVENT', resolver: 'EVENT_FIELD', path: 'event.venue', type: 'STRING' },
    { key: 'event.date_of_agm', label: 'Date Of AGM', domain: 'EVENT', resolver: 'EVENT_FIELD', path: 'event.date_of_agm', type: 'DATE', order: 11, formats: ['DD-MMM-YYYY', 'DD/MM/YYYY', 'YYYY-MM-DD'] },
    { key: 'event.agm_held_date', label: 'AGM Held Date', domain: 'EVENT', resolver: 'EVENT_FIELD', path: 'event.agm_held_date', type: 'DATE', order: 12, formats: ['DD-MMM-YYYY', 'DD/MM/YYYY', 'YYYY-MM-DD'] },
    { key: 'event.actual_fye', label: 'Actual Fye', domain: 'EVENT', resolver: 'EVENT_FIELD', path: 'event.actual_fye', type: 'DATE', order: 13, formats: ['DD-MMM-YYYY', 'DD/MM/YYYY', 'YYYY-MM-DD'] },
    { key: 'event.year_of_fye', label: 'Year Of Fye', domain: 'EVENT', resolver: 'EVENT_FIELD', path: 'event.year_of_fye', type: 'STRING', order: 14 },
    { key: 'event.first_fye_date', label: 'First FYE Date', domain: 'EVENT', resolver: 'EVENT_FIELD', path: 'event.first_fye_date', type: 'DATE', order: 15, formats: ['DD-MMM-YYYY', 'DD/MM/YYYY', 'YYYY-MM-DD'] },
    { key: 'event.last_fye_date', label: 'last FYE Date', domain: 'EVENT', resolver: 'EVENT_FIELD', path: 'event.last_fye_date', type: 'DATE', order: 16, formats: ['DD-MMM-YYYY', 'DD/MM/YYYY', 'YYYY-MM-DD'] },
    { key: 'event.last_date_of_month', label: 'Last date of the month', domain: 'EVENT', resolver: 'EVENT_FIELD', path: 'event.last_date_of_month', type: 'DATE', order: 17, formats: ['DD-MMM-YYYY', 'DD/MM/YYYY', 'YYYY-MM-DD'] },
    { key: 'event.chairman_name', label: 'Chairman Name', domain: 'EVENT', resolver: 'EVENT_FIELD', path: 'event.chairman_name', type: 'STRING', order: 18 },
    { key: 'common.bank_name', label: 'Bank Name', domain: 'COMMON', resolver: 'COMMON_FIELD', path: 'common.bank_name', type: 'STRING', order: 1 },
    { key: 'common.account_number', label: 'Account Number', domain: 'COMMON', resolver: 'COMMON_FIELD', path: 'common.account_number', type: 'STRING', order: 2 },
    { key: 'common.account_type', label: 'Account Type', domain: 'COMMON', resolver: 'COMMON_FIELD', path: 'common.account_type', type: 'STRING', order: 3 },
    { key: 'common.current_date', label: 'Current Date', domain: 'COMMON', resolver: 'SYSTEM_DATE', path: 'system.current_date', type: 'DATE', order: 4, formats: ['DD-MMM-YYYY', 'DD/MM/YYYY', 'YYYY-MM-DD'] },
]);
