'use strict';

const registry = Object.freeze({
    ENTITY_FIELD: Object.freeze([
        'entity.name',
        'entity.former_name',
        'entity.client_no',
        'entity.company_type_id', //Company type
    ]),

    COMPANY_DETAIL_FIELD: Object.freeze([
        'company_detail.company_incorporation_date',
        'company_detail.company_fin_date',
        'company_detail.country',
        // 'company_detail.ssic_id',
        // 'company_detail.ssic_user_description',
        // 'company_detail.ssic_id_secondary',
        // 'company_detail.ssic_user_description_secondary',
    ]),
    PRIMARY_IDENTIFICATION: Object.freeze(['identification.registration_number']),

    ENTITY_ADDRESS: Object.freeze([
        'addresses.registered',
        'addresses.local',
        'addresses.foreign',
    ]),
    ENTITY_CONTACT: Object.freeze(['contacts.primary_email']),
    COMPANY_PROFILE: Object.freeze([
        'company_profile.strike_off_or_dissolved_date',
        'company_profile.bank_name',
        'company_profile.ssic_code_1',
        'company_profile.ssic_description_1',
        'company_profile.ssic_code_2',
        'company_profile.ssic_description_2',
        'company_profile.new_name',
        'company_profile.old_name',
        'company_profile.old_name_effective_date',
        'company_profile.new_registered_address',
        'company_profile.old_registered_address',
        'company_profile.old_registered_address_effective_date',
    ]),
    CURRENT_OFFICIALS: Object.freeze([
        'officials.all',
        'officials.directors',
        'officials.secretaries',
        'officials.shareholders',
    ]),
    CURRENT_SHARES: Object.freeze(['shares.current']),
    SHARE_DETAIL: Object.freeze([
        'share_detail.shareholder_name',
        'share_detail.shareholder_address',
        'share_detail.shareholder_identification_type',
        'share_detail.shareholder_identification_number',
        'share_detail.currency',
        'share_detail.shareholder_nationality',
        'share_detail.shareholder_phone',
        'share_detail.shareholder_mobile',
        'share_detail.share_certificate_number',
        'share_detail.number_of_shares',
        'share_detail.price_per_share',
        'share_detail.number_of_shares_in_words',
        'share_detail.cash_paid_up_capital',
        'share_detail.cash_paid_up_capital_in_words',
        'share_detail.consideration_paid_up_capital',
        'share_detail.consideration_paid_up_capital_in_words',
        'share_detail.total_paid_up_capital',
        'share_detail.transferor_name',
        'share_detail.transferor_identification_type',
        'share_detail.transferor_identification_number',
        'share_detail.transferor_address',
        'share_detail.transferee_name',
        'share_detail.transferee_identification_type',
        'share_detail.transferee_identification_number',
        'share_detail.transferee_address',
        'share_detail.transfer_amount_of_shares',
    ]),
    SELECTED_OFFICIAL: Object.freeze([
        'official_record.name',
        'official_record.occupation',
        'official_record.date_of_birth',
        'official_record.nationality',
        'official_record.identification_number',
        'official_record.identification_type',
        'official_record.default_address',
        'official_record.alternate_address',
        'official_record.contact_number',
        'official_record.telephone',
        'official_record.role',
        'official_record.role_name',
        'official_record.appointment_date',
        'official_record.designation_or_occupation',
        'official_record.cessation_date',
        'official_record.status',
        'official_record.company_type',
        'official_record.country',
        'official_record.incorporation_date',
        'official_record.registered_company_address',
        'official_record.registration_number',
    ]),
    SELECTED_SHARE: Object.freeze([
        'share_record.share_class_name',
        'share_record.currency',
        'share_record.share_type',
        'share_record.number_of_shares',
        'share_record.issued_share_capital',
        'share_record.paid_up_capital',
        'share_record.per_share',
        'share_record.transaction_date',
    ]),
    EVENT_FIELD: Object.freeze([
        'event.event_slug',
        'event.period_start',
        'event.period_end',
        'event.fye_date',
        'event.due_date',
        'event.extended_due_date',
        'event.held_date',
        'event.filing_date',
        'event.status',
        'event.venue',
        'event.date_of_agm',
        'event.agm_held_date',
        'event.actual_fye',
        'event.year_of_fye',
        'event.first_fye_date',
        'event.last_fye_date',
        'event.last_date_of_month',
        'event.chairman_name',
    ]),
    COMMON_FIELD: Object.freeze([
        'common.bank_name',
        'common.account_number',
        'common.account_type',
    ]),
    SYSTEM_DATE: Object.freeze(['system.current_date']),
});

const isAllowedResolverPath = (resolverName, resolverPath) =>
    Boolean(registry[resolverName]?.includes(resolverPath));

module.exports = {
    registry,
    isAllowedResolverPath,
};
